SessionProperties :=

   'Top;'
 + 'Left;'
 + 'Width;'
 + 'Height;'
 + 'WindowState;'
 
 // MainMenu
 
 + 'MainMenu.Items;'
 
 + 'MainMenu_View_Toolbars_AddressBar.Checked;'
 
 + 'MainMenu_View_LargeIcons.Checked;'
 + 'MainMenu_View_SmallIcons.Checked;'
 + 'MainMenu_View_List.Checked;'
 + 'MainMenu_View_Report.Checked;'
 
 + 'MainMenu_View_RowSelect.Checked;'
 + 'MainMenu_View_GridLines.Checked;'
 + 'MainMenu_View_ListMode.Checked;'
 
 + 'MainMenu_View_OrderBy_Name.Checked;'
 + 'MainMenu_View_OrderBy_Crc.Checked;'
 + 'MainMenu_View_OrderBy_Path.Checked;'
 + 'MainMenu_View_OrderBy_Position.Checked;'
 + 'MainMenu_View_OrderBy_Size.Checked;'
 + 'MainMenu_View_OrderBy_Packed.Checked;'
 + 'MainMenu_View_OrderBy_Ratio.Checked;'
 + 'MainMenu_View_OrderBy_Type.Checked;'
 + 'MainMenu_View_OrderBy_Modified.Checked;'
 + 'MainMenu_View_OrderBy_Attributes.Checked;'
 + 'MainMenu_View_OrderBy_Method.Checked;'
 + 'MainMenu_View_OrderBy_Password.Checked;'

 + 'MainMenu_View_Details_Name.Checked;'
 + 'MainMenu_View_Details_CRC.Checked;'
 + 'MainMenu_View_Details_Path.Checked;'
 + 'MainMenu_View_Details_Position.Checked;'
 + 'MainMenu_View_Details_Size.Checked;'
 + 'MainMenu_View_Details_Packed.Checked;'
 + 'MainMenu_View_Details_Ratio.Checked;'
 + 'MainMenu_View_Details_Type.Checked;'
 + 'MainMenu_View_Details_Modified.Checked;'
 + 'MainMenu_View_Details_Attributes.Checked;'
 + 'MainMenu_View_Details_Method.Checked;'
 + 'MainMenu_View_Details_Password.Checked;'
 
 + 'MainMenu_Options_SaveOnExit.Checked;'
 + 'MainMenu_Options_LogReport.Checked;'

 // ArchiveListView

 + 'ArchiveListView.Columns;'
 + 'ArchiveListView.SortCol;'

 // PopupMenu Buttons

 + 'PopupMenu_Buttons_New.Checked;'
 + 'PopupMenu_Buttons_Open.Checked;'
 + 'PopupMenu_Buttons_N1.Checked;'
 + 'PopupMenu_Buttons_Add.Checked;'
 + 'PopupMenu_Buttons_Extract.Checked;'
 + 'PopupMenu_Buttons_View.Checked;'
 + 'PopupMenu_Buttons_Delete.Checked;'
 + 'PopupMenu_Buttons_N2.Checked;'
 + 'PopupMenu_Buttons_Test.Checked;'
 + 'PopupMenu_Buttons_CheckOut.Checked;'
 + 'PopupMenu_Buttons_N3.Checked;'
 + 'PopupMenu_Buttons_Configuration.Checked;'
 + 'PopupMenu_Buttons_Help.Checked;'
 + 'PopupMenu_Buttons_Exit.Checked;';


