SessionProperties :=

   'Top;'
 + 'Left;'
 + 'Width;'
 + 'Height;'
 + 'WindowState;'
 
 + 'MainMenu_View_LargeIcons.Checked;'
 + 'MainMenu_View_SmallIcons.Checked;'
 + 'MainMenu_View_List.Checked;'
 + 'MainMenu_View_Report.Checked;'
 
 + 'MainMenu_View_RowSelect.Checked;'
 + 'MainMenu_View_GridLines.Checked;'
 + 'MainMenu_View_ListMode.Checked;'


 + 'ArchiveListView.Columns;'
 + 'ArchiveListView.SortCol;'

 + 'PopupMenu_Buttons_New.Checked;'
 + 'PopupMenu_Buttons_Open.Checked;'
 + 'PopupMenu_Buttons_N1.Checked;'
 + 'PopupMenu_Buttons_Add.Checked;'
 + 'PopupMenu_Buttons_Extract.Checked;'
 + 'PopupMenu_Buttons_View.Checked;'
 + 'PopupMenu_Buttons_Delete.Checked;'
 + 'PopupMenu_Buttons_N2.Checked;'
 + 'PopupMenu_Buttons_Test.Checked;'
 + 'PopupMenu_Buttons_CheckOut.Checked;'
 + 'PopupMenu_Buttons_N3.Checked;'
 + 'PopupMenu_Buttons_Configuration.Checked;'
 + 'PopupMenu_Buttons_Help.Checked;'
 + 'PopupMenu_Buttons_Exit.Checked;';


