SessionProperties :=

   'Top;'
 + 'Left;'
 + 'Width;'
 + 'Height;'
 + 'WindowState;'

 + 'MainFrm_PopupMenu_Btns_Add.Checked;'
 + 'MainFrm_PopupMenu_Btns_CheckOut.Checked;'
 + 'MainFrm_PopupMenu_Btns_Config.Checked;'
 + 'MainFrm_PopupMenu_Btns_Delete.Checked;'
 + 'MainFrm_PopupMenu_Btns_Exit.Checked;'
 + 'MainFrm_PopupMenu_Btns_Extract.Checked;'
 + 'MainFrm_PopupMenu_Btns_Help.Checked;'
 + 'MainFrm_PopupMenu_Btns_N1.Checked;'
 + 'MainFrm_PopupMenu_Btns_N2.Checked;'
 + 'MainFrm_PopupMenu_Btns_N3.Checked;'
 + 'MainFrm_PopupMenu_Btns_New.Checked;'
 + 'MainFrm_PopupMenu_Btns_Open.Checked;'
 + 'MainFrm_PopupMenu_Btns_Test.Checked;'
 + 'MainFrm_PopupMenu_Btns_View.Checked;';
 
 {$IFDEF WINDOWS}
   MainFrm_ArchiveTreeView.BorderWidth := 0;
 {$ELSE}
   MainFrm_ArchiveTreeView.BorderWidth := 2;
 {$ENDIF}
  
